
export const homeObjOne = {
    id: 'discography',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topText: true,
    topLine: "Released August 6th, 2021",
    headline: "Cerebral Fountain out now via Helix Audio",
    description: "Coming out of a global pandemic that halted any touring for the Pink Cloud Summer record, Skybound refused to let the turn of events slow down their creative process and immediately began work on their most colorful and complex album yet. Channeling a new found creative freedom, the aim was to create uncompromising hooks with tried and true technical proficiency while spreading the wings of what Skybound is capable of doing. The result is nine unique tracks that reconnect ears and minds with the outdoors and the beautiful surroundings we often forget to appreciate. Largely self produced and mastered by Acle Kahney (TesseracT), it’s a movie score infused rock trip through vast expanses and far away lands.",
    buttonLabel: 'music videos',
    imgStart: false,
    img: require('../images/covers/cf.png'),
    alt: 'headbanging guitar solo',
    dark: false,
    primary: true,
    darkText: true,
};
export const homeObjTwo = {
    id: 'discography',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topText: false,
    topLine: "Released July 17, 2020",
    headline: "Pink Cloud Summer (2020) (EP)",
    description: "Coming out of a global pandemic that halted any touring for the Pink Cloud Summer record, Skybound refused to let the turn of events slow down their creative process and immediately began work on their most colorful and complex album yet. Channeling a new found creative freedom, the aim was to create uncompromising hooks with tried and true technical proficiency while spreading the wings of what Skybound is capable of doing. The result is nine unique tracks that reconnect ears and minds with the outdoors and the beautiful surroundings we often forget to appreciate. Largely self produced and mastered by Acle Kahney (TesseracT), it’s a movie score infused rock trip through vast expanses and far away lands.",
    buttonLabel: 'music videos',
    imgStart: true,
    img: require('../images/covers/pcs.png'),
    alt: 'headbanging guitar solo',
    dark: false,
    primary: false,
    darkText: false,
};

export const homeObjThree = {
    id: 'discography',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topText: true,
    topLine: "Released June 15, 2018",
    headline: "For All the Hope we Hold (2018) (LP)",
    description: "Having played in previous bands of various styles for the past handful of years, Tiago Santos and Jamison Tomka opted to start fresh, breaking all the restrictions of adhering to strict genre and style rules. Pulling from rock, metal, orchestral soundtrack, ambient music and electronic, they aimed to create an album and a band of diverse taste and sound. The result is 2018’s “For All the Hope We Hold”, a reverb laden journey of a band taking its first steps and finding its place within instrumental music.",
    buttonLabel: 'music videos',
    imgStart: false,
    img: require('../images/covers/hwh.png'),
    alt: 'headbanging guitar solo',
    dark: false,
    primary: false,
    darkText: true,
};
